services:
  db:
    image: postgres:17
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - docker-fastapi-base

volumes:
  db-data:

networks:
  docker-fastapi-base:
    driver: bridge
