"""make shift.role_id non-null

Revision ID: 41f0f779f959
Revises: 8c24e7a7db90
Create Date: 2025-11-26 15:31:06.024887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f0f779f959'
down_revision: Union[str, None] = '8c24e7a7db90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM shifts WHERE role_id IS NULL"))

    op.alter_column('shifts', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('shifts_role_id_fkey', 'shifts', type_='foreignkey')
    op.create_foreign_key(None, 'shifts', 'job_roles', ['role_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.create_foreign_key('shifts_role_id_fkey', 'shifts', 'job_roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.alter_column('shifts', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
