"""default timezone

Revision ID: 688ab92e9693
Revises: 6f043a8a8ae4
Create Date: 2025-10-31 16:35:58.137492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688ab92e9693'
down_revision: Union[str, None] = '6f043a8a8ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('required_staff_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('start_time <> end_time', name='ck_weeklytpl_nonzero'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_weeklytpl_weekday'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['job_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'weekday', 'location_id', 'role_id', 'start_time', 'end_time', name='uq_weeklytpl_slot')
    )
    op.create_index(op.f('ix_weekly_template_items_location_id'), 'weekly_template_items', ['location_id'], unique=False)
    op.create_index(op.f('ix_weekly_template_items_org_id'), 'weekly_template_items', ['org_id'], unique=False)
    op.create_index(op.f('ix_weekly_template_items_role_id'), 'weekly_template_items', ['role_id'], unique=False)
    op.create_index(op.f('ix_weekly_template_items_schedule_id'), 'weekly_template_items', ['schedule_id'], unique=False)
    op.create_index('ix_weeklytpl_sched_weekday', 'weekly_template_items', ['schedule_id', 'weekday'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weeklytpl_sched_weekday', table_name='weekly_template_items')
    op.drop_index(op.f('ix_weekly_template_items_schedule_id'), table_name='weekly_template_items')
    op.drop_index(op.f('ix_weekly_template_items_role_id'), table_name='weekly_template_items')
    op.drop_index(op.f('ix_weekly_template_items_org_id'), table_name='weekly_template_items')
    op.drop_index(op.f('ix_weekly_template_items_location_id'), table_name='weekly_template_items')
    op.drop_table('weekly_template_items')
    # ### end Alembic commands ###
