"""add assignments table and required_staff_count on shifts

Revision ID: 6f043a8a8ae4
Revises: d8f69a0ce087
Create Date: 2025-10-27 23:25:50.968534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f043a8a8ae4'
down_revision: Union[str, None] = 'd8f69a0ce087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assignments_shift_id'), 'assignments', ['shift_id'], unique=False)
    op.drop_column('assignments', 'preference_score')
    op.add_column(
        "shifts",
        sa.Column("required_staff_count", sa.Integer(), nullable=False, server_default="1"),
    )
    op.alter_column("shifts", "required_staff_count", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'required_staff_count')
    op.add_column('assignments', sa.Column('preference_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_assignments_shift_id'), table_name='assignments')
    # ### end Alembic commands ###
