"""Max_hour_cap

Revision ID: 8c24e7a7db90
Revises: 688ab92e9693
Create Date: 2025-10-31 18:50:46.953939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c24e7a7db90'
down_revision: Union[str, None] = '688ab92e9693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_roles', sa.Column('weekly_hours_cap', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_roles', 'weekly_hours_cap')
    # ### end Alembic commands ###
