"""replace availability with unavailability

Revision ID: ff269b05452c
Revises: 9ac4cc1cd4e1
Create Date: 2025-10-13 22:43:09.209824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff269b05452c'
down_revision: Union[str, None] = '9ac4cc1cd4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unavailability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'start_at', 'end_at', name='unique_unavailable_exact')
    )
    op.create_index('ix_unavail_emp_start', 'unavailability', ['employee_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_unavailability_employee_id'), 'unavailability', ['employee_id'], unique=False)
    op.drop_index('ix_availability_employee_id', table_name='availability')
    op.drop_table('availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weekday', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='availability_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='availability_pkey'),
    sa.UniqueConstraint('employee_id', 'weekday', 'start_time', 'end_time', name='unique_availability_slot')
    )
    op.create_index('ix_availability_employee_id', 'availability', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_unavailability_employee_id'), table_name='unavailability')
    op.drop_index('ix_unavail_emp_start', table_name='unavailability')
    op.drop_table('unavailability')
    # ### end Alembic commands ###
